// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using CoreSRE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreSRE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213104156_ChangeAllowedToolsToJsonb")]
    partial class ChangeAllowedToolsToJsonb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreSRE.Domain.Entities.AgentRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agent_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkflowRef")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_ref");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent_registrations", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.AgentSessionRecord", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("agent_id");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonElement>("SessionData")
                        .HasColumnType("jsonb")
                        .HasColumnName("session_data");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AgentId", "ConversationId");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_agent_sessions_agent_id");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_conversations_agent_id");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_conversations_updated_at");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.LlmProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string>("DiscoveredModels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("discovered_models");

                    b.Property<DateTime?>("ModelsRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("models_refreshed_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("llm_providers", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.McpToolItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<JsonElement?>("InputSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_schema");

                    b.Property<JsonElement?>("OutputSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_schema");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_name");

                    b.Property<Guid>("ToolRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_registration_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ToolRegistrationId");

                    b.HasIndex("ToolRegistrationId", "ToolName")
                        .IsUnique();

                    b.ToTable("mcp_tool_items", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.SandboxInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<int>("AutoStopMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("auto_stop_minutes");

                    b.Property<int>("CpuCores")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_cores");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("image");

                    b.Property<string>("K8sNamespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("k8s_namespace");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<int>("MemoryMib")
                        .HasColumnType("integer")
                        .HasColumnName("memory_mib");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<bool>("PersistWorkspace")
                        .HasColumnType("boolean")
                        .HasColumnName("persist_workspace");

                    b.Property<string>("PodName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pod_name");

                    b.Property<string>("SandboxType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sandbox_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("Status");

                    b.ToTable("sandbox_instances", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.SkillRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string>("AllowedTools")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_tools");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("Compatibility")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("compatibility");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HasFiles")
                        .HasColumnType("boolean")
                        .HasColumnName("has_files");

                    b.Property<string>("License")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("license");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string>("RequiresTools")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requires_tools");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Scope");

                    b.HasIndex("Status");

                    b.ToTable("skill_registrations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            AllowedTools = "[]",
                            Category = "SRE",
                            Content = "# Incident Response Skill\r\n\r\n## Purpose\r\nGuide the SRE through a structured incident response process, from initial triage\r\nto resolution and post-mortem documentation.\r\n\r\n## Workflow\r\n\r\n### 1. Triage\r\n- Gather initial facts: service affected, error symptoms, blast radius\r\n- Classify severity: SEV1 (critical), SEV2 (major), SEV3 (minor), SEV4 (cosmetic)\r\n- Identify on-call responders and communication channels\r\n\r\n### 2. Investigation\r\n- Check monitoring dashboards and recent deployments\r\n- Review error logs and metrics for anomalies\r\n- Identify potential root causes\r\n\r\n### 3. Mitigation\r\n- Propose immediate actions: rollback, feature flag toggle, scaling\r\n- Coordinate with relevant teams\r\n- Verify mitigation effectiveness\r\n\r\n### 4. Communication\r\n- Draft status page updates for stakeholders\r\n- Prepare internal Slack/Teams messages with timeline\r\n- Schedule follow-up check-ins\r\n\r\n### 5. Post-Mortem\r\n- Document timeline of events\r\n- Identify root cause and contributing factors\r\n- Propose action items with owners and deadlines\r\n- Generate blameless post-mortem report\r\n\r\n## Output Format\r\nAlways provide structured responses with:\r\n- Current phase indicator\r\n- Action items list\r\n- Severity and status summary",
                            CreatedAt = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Guide through incident triage, severity classification, communication templates, and post-mortem facilitation.",
                            HasFiles = false,
                            Name = "incident-response",
                            RequiresTools = "[]",
                            Scope = "Builtin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            AllowedTools = "[]",
                            Category = "Development",
                            Content = "# Code Review Skill\r\n\r\n## Purpose\r\nPerform thorough, systematic code reviews focusing on correctness, security,\r\nperformance, and maintainability.\r\n\r\n## Review Checklist\r\n\r\n### Correctness\r\n- Logic errors, off-by-one, null handling\r\n- Edge cases and boundary conditions\r\n- Error handling completeness\r\n\r\n### Security\r\n- Input validation and sanitization\r\n- SQL injection, XSS, CSRF vulnerabilities\r\n- Secrets/credentials in code\r\n- Authentication/authorization gaps\r\n\r\n### Performance\r\n- N+1 queries, unnecessary allocations\r\n- Missing indexes for database queries\r\n- Caching opportunities\r\n- Async/await usage correctness\r\n\r\n### Maintainability\r\n- Code clarity and naming conventions\r\n- SOLID principles adherence\r\n- Test coverage for new/changed logic\r\n- Documentation for public APIs\r\n\r\n## Output Format\r\nProvide findings categorized by severity:\r\n- 🔴 Critical: Must fix before merge\r\n- 🟡 Warning: Should fix, potential issues\r\n- 🔵 Suggestion: Nice-to-have improvements\r\n- 💡 Note: Informational observations",
                            CreatedAt = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perform systematic code review: check style, security, performance, and suggest improvements.",
                            HasFiles = false,
                            Name = "code-review",
                            RequiresTools = "[]",
                            Scope = "Builtin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            AllowedTools = "[]",
                            Category = "Database",
                            Content = "# Database Operations Skill\r\n\r\n## Purpose\r\nAssist with database administration tasks including query optimization,\r\nschema migration planning, and backup/restore operations.\r\n\r\n## Capabilities\r\n\r\n### Query Optimization\r\n- Analyze EXPLAIN/EXPLAIN ANALYZE output\r\n- Suggest index creation strategies\r\n- Rewrite inefficient queries\r\n- Identify missing statistics and vacuum needs\r\n\r\n### Migration Planning\r\n- Generate safe migration scripts (up + down)\r\n- Plan zero-downtime schema changes\r\n- Identify backward-compatible migration patterns\r\n- Estimate migration duration for large tables\r\n\r\n### Backup & Restore\r\n- Design backup strategies (full, incremental, WAL archiving)\r\n- Test restore procedures\r\n- Point-in-time recovery planning\r\n- Cross-region replication setup\r\n\r\n### Monitoring\r\n- Connection pool analysis\r\n- Slow query log review\r\n- Lock contention diagnosis\r\n- Storage and growth projections\r\n\r\n## Supported Databases\r\nPostgreSQL (primary), MySQL, SQL Server, MongoDB\r\n\r\n## Safety Rules\r\n- Never run destructive operations without explicit confirmation\r\n- Always generate rollback scripts with migrations\r\n- Prefer `IF EXISTS` / `IF NOT EXISTS` guards",
                            CreatedAt = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assist with database operations: query optimization, migration planning, backup/restore procedures.",
                            HasFiles = false,
                            Name = "database-ops",
                            RequiresTools = "[]",
                            Scope = "Builtin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            AllowedTools = "[]",
                            Category = "Infrastructure",
                            Content = "# Kubernetes Operations Skill\r\n\r\n## Purpose\r\nAssist with Kubernetes cluster management, workload troubleshooting,\r\nand infrastructure-as-code generation.\r\n\r\n## Capabilities\r\n\r\n### Troubleshooting\r\n- Diagnose CrashLoopBackOff, ImagePullBackOff, OOMKilled\r\n- Analyze pod events and container logs\r\n- Debug networking issues (DNS, Services, Ingress)\r\n- Investigate resource quota exhaustion\r\n\r\n### Resource Management\r\n- Right-size CPU/memory requests and limits\r\n- Configure HPA (Horizontal Pod Autoscaler)\r\n- Plan node pool sizing and scaling\r\n- Cost optimization recommendations\r\n\r\n### YAML Generation\r\n- Generate Deployment, Service, Ingress manifests\r\n- Create ConfigMap/Secret templates\r\n- Design RBAC policies (Role, ClusterRole, Bindings)\r\n- Write Helm chart templates\r\n\r\n### Operations\r\n- Rolling update strategies and rollback procedures\r\n- Blue-green and canary deployment patterns\r\n- Cluster upgrade planning\r\n- etcd backup and maintenance\r\n\r\n## Output Format\r\n- YAML manifests should be complete and ready to apply\r\n- Include namespace annotations\r\n- Add resource labels following conventions",
                            CreatedAt = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Help with Kubernetes cluster operations: troubleshooting pods, scaling, resource management, and YAML generation.",
                            HasFiles = false,
                            Name = "kubernetes-ops",
                            RequiresTools = "[]",
                            Scope = "Builtin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            AllowedTools = "[]",
                            Category = "Observability",
                            Content = "# Monitoring & Alerting Skill\r\n\r\n## Purpose\r\nHelp design effective monitoring strategies, create alerting rules,\r\nand define SLOs for service reliability.\r\n\r\n## Capabilities\r\n\r\n### Dashboard Design\r\n- RED method dashboards (Rate, Errors, Duration)\r\n- USE method dashboards (Utilization, Saturation, Errors)\r\n- Four Golden Signals implementation\r\n- Custom business metric dashboards\r\n\r\n### Alert Rules\r\n- Multi-window multi-burn-rate SLO alerts\r\n- Symptom-based alerting (avoid cause-based)\r\n- Alert routing and escalation policies\r\n- Reduce noise: grouping, inhibition, silencing\r\n\r\n### SLO Definition\r\n- Identify critical user journeys\r\n- Define SLI (Service Level Indicators)\r\n- Set SLO targets with error budgets\r\n- Calculate error budget burn rates\r\n\r\n### Supported Platforms\r\n- Prometheus + Grafana (PromQL)\r\n- Datadog (DQL)\r\n- Azure Monitor (KQL)\r\n- CloudWatch (Metrics Insights)\r\n\r\n## Output Format\r\n- Alert rules in platform-native syntax\r\n- SLO specs with calculation formulas\r\n- Dashboard JSON/YAML for import",
                            CreatedAt = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Design and optimize monitoring dashboards, alerting rules, and SLO definitions.",
                            HasFiles = false,
                            Name = "monitoring-alerting",
                            RequiresTools = "[]",
                            Scope = "Builtin",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.ToolRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DiscoveryError")
                        .HasColumnType("text")
                        .HasColumnName("discovery_error");

                    b.Property<string>("ImportSource")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("import_source");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tool_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ToolType");

                    b.ToTable("tool_registrations", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.WorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<JsonElement>("Input")
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<JsonElement?>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("workflow_executions", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.AgentRegistration", b =>
                {
                    b.OwnsOne("CoreSRE.Domain.ValueObjects.AgentCardVO", "AgentCard", b1 =>
                        {
                            b1.Property<Guid>("AgentRegistrationId");

                            b1.HasKey("AgentRegistrationId");

                            b1.ToTable("agent_registrations");

                            b1
                                .ToJson("agent_card")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationId");

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.AgentInterfaceVO", "Interfaces", b2 =>
                                {
                                    b2.Property<Guid>("AgentCardVOAgentRegistrationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Path");

                                    b2.Property<string>("Protocol")
                                        .IsRequired();

                                    b2.HasKey("AgentCardVOAgentRegistrationId", "__synthesizedOrdinal");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("AgentCardVOAgentRegistrationId");
                                });

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.AgentSkillVO", "Skills", b2 =>
                                {
                                    b2.Property<Guid>("AgentCardVOAgentRegistrationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Description");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("AgentCardVOAgentRegistrationId", "__synthesizedOrdinal");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("AgentCardVOAgentRegistrationId");
                                });

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.SecuritySchemeVO", "SecuritySchemes", b2 =>
                                {
                                    b2.Property<Guid>("AgentCardVOAgentRegistrationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Parameters");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.HasKey("AgentCardVOAgentRegistrationId", "__synthesizedOrdinal");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("AgentCardVOAgentRegistrationId");
                                });

                            b1.Navigation("Interfaces");

                            b1.Navigation("SecuritySchemes");

                            b1.Navigation("Skills");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.HealthCheckVO", "HealthCheck", b1 =>
                        {
                            b1.Property<Guid>("AgentRegistrationId");

                            b1.Property<int>("FailureCount");

                            b1.Property<bool>("IsHealthy");

                            b1.Property<DateTime?>("LastCheckTime");

                            b1.HasKey("AgentRegistrationId");

                            b1.ToTable("agent_registrations");

                            b1
                                .ToJson("health_check")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationId");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.LlmConfigVO", "LlmConfig", b1 =>
                        {
                            b1.Property<Guid>("AgentRegistrationId");

                            b1.Property<bool?>("AllowMultipleToolCalls");

                            b1.Property<int?>("EmbeddingDimensions");

                            b1.Property<string>("EmbeddingModelId");

                            b1.Property<Guid?>("EmbeddingProviderId");

                            b1.Property<bool?>("EnableChatHistory");

                            b1.Property<bool?>("EnableSandbox");

                            b1.Property<bool?>("EnableSemanticMemory");

                            b1.Property<float?>("FrequencyPenalty");

                            b1.Property<string>("Instructions");

                            b1.Property<int?>("MaxHistoryMessages");

                            b1.Property<int?>("MaxOutputTokens");

                            b1.Property<int?>("MemoryMaxResults");

                            b1.Property<double?>("MemoryMinRelevanceScore");

                            b1.Property<string>("MemorySearchMode");

                            b1.Property<string>("ModelId")
                                .IsRequired();

                            b1.Property<float?>("PresencePenalty");

                            b1.Property<Guid?>("ProviderId");

                            b1.Property<string>("ResponseFormat");

                            b1.Property<string>("ResponseFormatSchema");

                            b1.Property<int?>("SandboxCpus");

                            b1.Property<string>("SandboxImage");

                            b1.Property<Guid?>("SandboxInstanceId");

                            b1.Property<string>("SandboxK8sNamespace");

                            b1.Property<int?>("SandboxMemoryMib");

                            b1.Property<string>("SandboxMode");

                            b1.Property<string>("SandboxType");

                            b1.Property<long?>("Seed");

                            b1.PrimitiveCollection<string>("SkillRefs")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("StopSequences");

                            b1.Property<float?>("Temperature");

                            b1.Property<string>("ToolMode");

                            b1.PrimitiveCollection<string>("ToolRefs")
                                .IsRequired();

                            b1.Property<int?>("TopK");

                            b1.Property<float?>("TopP");

                            b1.HasKey("AgentRegistrationId");

                            b1.ToTable("agent_registrations");

                            b1
                                .ToJson("llm_config")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationId");
                        });

                    b.Navigation("AgentCard");

                    b.Navigation("HealthCheck")
                        .IsRequired();

                    b.Navigation("LlmConfig");
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("CoreSRE.Domain.Entities.AgentRegistration", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.McpToolItem", b =>
                {
                    b.HasOne("CoreSRE.Domain.Entities.ToolRegistration", "ToolRegistration")
                        .WithMany("McpToolItems")
                        .HasForeignKey("ToolRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.ToolAnnotationsVO", "Annotations", b1 =>
                        {
                            b1.Property<Guid>("McpToolItemId");

                            b1.Property<bool>("Destructive");

                            b1.Property<bool>("Idempotent");

                            b1.Property<bool>("OpenWorldHint");

                            b1.Property<bool>("ReadOnly");

                            b1.HasKey("McpToolItemId");

                            b1.ToTable("mcp_tool_items");

                            b1
                                .ToJson("annotations")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("McpToolItemId");
                        });

                    b.Navigation("Annotations");

                    b.Navigation("ToolRegistration");
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.ToolRegistration", b =>
                {
                    b.OwnsOne("CoreSRE.Domain.ValueObjects.AuthConfigVO", "AuthConfig", b1 =>
                        {
                            b1.Property<Guid>("ToolRegistrationId");

                            b1.Property<string>("ApiKeyHeaderName");

                            b1.Property<string>("AuthType")
                                .IsRequired();

                            b1.Property<string>("ClientId");

                            b1.Property<string>("EncryptedClientSecret");

                            b1.Property<string>("EncryptedCredential");

                            b1.Property<string>("TokenEndpoint");

                            b1.HasKey("ToolRegistrationId");

                            b1.ToTable("tool_registrations");

                            b1
                                .ToJson("auth_config")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ToolRegistrationId");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.ConnectionConfigVO", "ConnectionConfig", b1 =>
                        {
                            b1.Property<Guid>("ToolRegistrationId");

                            b1.Property<string>("Endpoint")
                                .IsRequired();

                            b1.Property<string>("HttpMethod")
                                .IsRequired();

                            b1.Property<string>("TransportType")
                                .IsRequired();

                            b1.HasKey("ToolRegistrationId");

                            b1.ToTable("tool_registrations");

                            b1
                                .ToJson("connection_config")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ToolRegistrationId");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.ToolSchemaVO", "ToolSchema", b1 =>
                        {
                            b1.Property<Guid>("ToolRegistrationId");

                            b1.Property<string>("InputSchema");

                            b1.Property<string>("OutputSchema");

                            b1.HasKey("ToolRegistrationId");

                            b1.ToTable("tool_registrations");

                            b1
                                .ToJson("tool_schema")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ToolRegistrationId");

                            b1.OwnsOne("CoreSRE.Domain.ValueObjects.ToolAnnotationsVO", "Annotations", b2 =>
                                {
                                    b2.Property<Guid>("ToolSchemaVOToolRegistrationId");

                                    b2.Property<bool>("Destructive");

                                    b2.Property<bool>("Idempotent");

                                    b2.Property<bool>("OpenWorldHint");

                                    b2.Property<bool>("ReadOnly");

                                    b2.HasKey("ToolSchemaVOToolRegistrationId");

                                    b2.ToTable("tool_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("ToolSchemaVOToolRegistrationId");
                                });

                            b1.Navigation("Annotations");
                        });

                    b.Navigation("AuthConfig")
                        .IsRequired();

                    b.Navigation("ConnectionConfig")
                        .IsRequired();

                    b.Navigation("ToolSchema");
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.OwnsOne("CoreSRE.Domain.ValueObjects.WorkflowGraphVO", "Graph", b1 =>
                        {
                            b1.Property<Guid>("WorkflowDefinitionId");

                            b1.HasKey("WorkflowDefinitionId");

                            b1.ToTable("workflow_definitions");

                            b1
                                .ToJson("graph")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowDefinitionId");

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.WorkflowEdgeVO", "Edges", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowGraphVOWorkflowDefinitionId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Condition");

                                    b2.Property<string>("EdgeId")
                                        .IsRequired();

                                    b2.Property<string>("EdgeType")
                                        .IsRequired();

                                    b2.Property<string>("SourceNodeId")
                                        .IsRequired();

                                    b2.Property<int>("SourcePortIndex");

                                    b2.Property<string>("TargetNodeId")
                                        .IsRequired();

                                    b2.Property<int>("TargetPortIndex");

                                    b2.HasKey("WorkflowGraphVOWorkflowDefinitionId", "__synthesizedOrdinal");

                                    b2.ToTable("workflow_definitions");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowGraphVOWorkflowDefinitionId");
                                });

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.WorkflowNodeVO", "Nodes", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowGraphVOWorkflowDefinitionId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Config");

                                    b2.Property<string>("DisplayName")
                                        .IsRequired();

                                    b2.Property<int>("InputCount");

                                    b2.Property<string>("NodeId")
                                        .IsRequired();

                                    b2.Property<string>("NodeType")
                                        .IsRequired();

                                    b2.Property<int>("OutputCount");

                                    b2.Property<Guid?>("ReferenceId");

                                    b2.HasKey("WorkflowGraphVOWorkflowDefinitionId", "__synthesizedOrdinal");

                                    b2.ToTable("workflow_definitions");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowGraphVOWorkflowDefinitionId");
                                });

                            b1.Navigation("Edges");

                            b1.Navigation("Nodes");
                        });

                    b.Navigation("Graph")
                        .IsRequired();
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.WorkflowExecution", b =>
                {
                    b.OwnsOne("CoreSRE.Domain.ValueObjects.WorkflowGraphVO", "GraphSnapshot", b1 =>
                        {
                            b1.Property<Guid>("WorkflowExecutionId");

                            b1.HasKey("WorkflowExecutionId");

                            b1.ToTable("workflow_executions");

                            b1
                                .ToJson("graph_snapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowExecutionId");

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.WorkflowEdgeVO", "Edges", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowGraphVOWorkflowExecutionId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Condition");

                                    b2.Property<string>("EdgeId")
                                        .IsRequired();

                                    b2.Property<string>("EdgeType")
                                        .IsRequired();

                                    b2.Property<string>("SourceNodeId")
                                        .IsRequired();

                                    b2.Property<int>("SourcePortIndex");

                                    b2.Property<string>("TargetNodeId")
                                        .IsRequired();

                                    b2.Property<int>("TargetPortIndex");

                                    b2.HasKey("WorkflowGraphVOWorkflowExecutionId", "__synthesizedOrdinal");

                                    b2.ToTable("workflow_executions");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowGraphVOWorkflowExecutionId");
                                });

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.WorkflowNodeVO", "Nodes", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowGraphVOWorkflowExecutionId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Config");

                                    b2.Property<string>("DisplayName")
                                        .IsRequired();

                                    b2.Property<int>("InputCount");

                                    b2.Property<string>("NodeId")
                                        .IsRequired();

                                    b2.Property<string>("NodeType")
                                        .IsRequired();

                                    b2.Property<int>("OutputCount");

                                    b2.Property<Guid?>("ReferenceId");

                                    b2.HasKey("WorkflowGraphVOWorkflowExecutionId", "__synthesizedOrdinal");

                                    b2.ToTable("workflow_executions");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowGraphVOWorkflowExecutionId");
                                });

                            b1.Navigation("Edges");

                            b1.Navigation("Nodes");
                        });

                    b.OwnsMany("CoreSRE.Domain.ValueObjects.NodeExecutionVO", "NodeExecutions", b1 =>
                        {
                            b1.Property<Guid>("WorkflowExecutionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime?>("CompletedAt");

                            b1.Property<string>("ErrorMessage");

                            b1.Property<string>("Input");

                            b1.Property<string>("NodeId")
                                .IsRequired();

                            b1.Property<string>("Output");

                            b1.Property<DateTime?>("StartedAt");

                            b1.Property<string>("Status")
                                .IsRequired();

                            b1.HasKey("WorkflowExecutionId", "__synthesizedOrdinal");

                            b1.ToTable("workflow_executions");

                            b1
                                .ToJson("node_executions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowExecutionId");
                        });

                    b.Navigation("GraphSnapshot")
                        .IsRequired();

                    b.Navigation("NodeExecutions");
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.ToolRegistration", b =>
                {
                    b.Navigation("McpToolItems");
                });
#pragma warning restore 612, 618
        }
    }
}
