// <auto-generated />
using System;
using System.Text.Json;
using CoreSRE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreSRE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211054457_AddWorkflowDefinition")]
    partial class AddWorkflowDefinition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreSRE.Domain.Entities.AgentRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agent_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkflowRef")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_ref");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent_registrations", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.AgentSessionRecord", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("agent_id");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonElement>("SessionData")
                        .HasColumnType("jsonb")
                        .HasColumnName("session_data");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AgentId", "ConversationId");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_agent_sessions_agent_id");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_conversations_agent_id");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_conversations_updated_at");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.LlmProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string>("DiscoveredModels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("discovered_models");

                    b.Property<DateTime?>("ModelsRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("models_refreshed_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("llm_providers", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.McpToolItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<JsonElement?>("InputSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_schema");

                    b.Property<JsonElement?>("OutputSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_schema");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_name");

                    b.Property<Guid>("ToolRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_registration_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ToolRegistrationId");

                    b.HasIndex("ToolRegistrationId", "ToolName")
                        .IsUnique();

                    b.ToTable("mcp_tool_items", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.ToolRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DiscoveryError")
                        .HasColumnType("text")
                        .HasColumnName("discovery_error");

                    b.Property<string>("ImportSource")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("import_source");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tool_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ToolType");

                    b.ToTable("tool_registrations", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.AgentRegistration", b =>
                {
                    b.OwnsOne("CoreSRE.Domain.ValueObjects.AgentCardVO", "AgentCard", b1 =>
                        {
                            b1.Property<Guid>("AgentRegistrationId");

                            b1.HasKey("AgentRegistrationId");

                            b1.ToTable("agent_registrations");

                            b1
                                .ToJson("agent_card")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationId");

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.AgentInterfaceVO", "Interfaces", b2 =>
                                {
                                    b2.Property<Guid>("AgentCardVOAgentRegistrationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Path");

                                    b2.Property<string>("Protocol")
                                        .IsRequired();

                                    b2.HasKey("AgentCardVOAgentRegistrationId", "__synthesizedOrdinal");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("AgentCardVOAgentRegistrationId");
                                });

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.AgentSkillVO", "Skills", b2 =>
                                {
                                    b2.Property<Guid>("AgentCardVOAgentRegistrationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Description");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("AgentCardVOAgentRegistrationId", "__synthesizedOrdinal");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("AgentCardVOAgentRegistrationId");
                                });

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.SecuritySchemeVO", "SecuritySchemes", b2 =>
                                {
                                    b2.Property<Guid>("AgentCardVOAgentRegistrationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Parameters");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.HasKey("AgentCardVOAgentRegistrationId", "__synthesizedOrdinal");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("AgentCardVOAgentRegistrationId");
                                });

                            b1.Navigation("Interfaces");

                            b1.Navigation("SecuritySchemes");

                            b1.Navigation("Skills");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.HealthCheckVO", "HealthCheck", b1 =>
                        {
                            b1.Property<Guid>("AgentRegistrationId");

                            b1.Property<int>("FailureCount");

                            b1.Property<bool>("IsHealthy");

                            b1.Property<DateTime?>("LastCheckTime");

                            b1.HasKey("AgentRegistrationId");

                            b1.ToTable("agent_registrations");

                            b1
                                .ToJson("health_check")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationId");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.LlmConfigVO", "LlmConfig", b1 =>
                        {
                            b1.Property<Guid>("AgentRegistrationId");

                            b1.Property<string>("Instructions");

                            b1.Property<string>("ModelId")
                                .IsRequired();

                            b1.Property<Guid?>("ProviderId");

                            b1.PrimitiveCollection<string>("ToolRefs")
                                .IsRequired();

                            b1.HasKey("AgentRegistrationId");

                            b1.ToTable("agent_registrations");

                            b1
                                .ToJson("llm_config")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationId");
                        });

                    b.Navigation("AgentCard");

                    b.Navigation("HealthCheck")
                        .IsRequired();

                    b.Navigation("LlmConfig");
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("CoreSRE.Domain.Entities.AgentRegistration", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.McpToolItem", b =>
                {
                    b.HasOne("CoreSRE.Domain.Entities.ToolRegistration", "ToolRegistration")
                        .WithMany("McpToolItems")
                        .HasForeignKey("ToolRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.ToolAnnotationsVO", "Annotations", b1 =>
                        {
                            b1.Property<Guid>("McpToolItemId");

                            b1.Property<bool>("Destructive");

                            b1.Property<bool>("Idempotent");

                            b1.Property<bool>("OpenWorldHint");

                            b1.Property<bool>("ReadOnly");

                            b1.HasKey("McpToolItemId");

                            b1.ToTable("mcp_tool_items");

                            b1
                                .ToJson("annotations")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("McpToolItemId");
                        });

                    b.Navigation("Annotations");

                    b.Navigation("ToolRegistration");
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.ToolRegistration", b =>
                {
                    b.OwnsOne("CoreSRE.Domain.ValueObjects.AuthConfigVO", "AuthConfig", b1 =>
                        {
                            b1.Property<Guid>("ToolRegistrationId");

                            b1.Property<string>("ApiKeyHeaderName");

                            b1.Property<string>("AuthType")
                                .IsRequired();

                            b1.Property<string>("ClientId");

                            b1.Property<string>("EncryptedClientSecret");

                            b1.Property<string>("EncryptedCredential");

                            b1.Property<string>("TokenEndpoint");

                            b1.HasKey("ToolRegistrationId");

                            b1.ToTable("tool_registrations");

                            b1
                                .ToJson("auth_config")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ToolRegistrationId");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.ConnectionConfigVO", "ConnectionConfig", b1 =>
                        {
                            b1.Property<Guid>("ToolRegistrationId");

                            b1.Property<string>("Endpoint")
                                .IsRequired();

                            b1.Property<string>("HttpMethod")
                                .IsRequired();

                            b1.Property<string>("TransportType")
                                .IsRequired();

                            b1.HasKey("ToolRegistrationId");

                            b1.ToTable("tool_registrations");

                            b1
                                .ToJson("connection_config")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ToolRegistrationId");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.ToolSchemaVO", "ToolSchema", b1 =>
                        {
                            b1.Property<Guid>("ToolRegistrationId");

                            b1.Property<string>("InputSchema");

                            b1.Property<string>("OutputSchema");

                            b1.HasKey("ToolRegistrationId");

                            b1.ToTable("tool_registrations");

                            b1
                                .ToJson("tool_schema")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ToolRegistrationId");

                            b1.OwnsOne("CoreSRE.Domain.ValueObjects.ToolAnnotationsVO", "Annotations", b2 =>
                                {
                                    b2.Property<Guid>("ToolSchemaVOToolRegistrationId");

                                    b2.Property<bool>("Destructive");

                                    b2.Property<bool>("Idempotent");

                                    b2.Property<bool>("OpenWorldHint");

                                    b2.Property<bool>("ReadOnly");

                                    b2.HasKey("ToolSchemaVOToolRegistrationId");

                                    b2.ToTable("tool_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("ToolSchemaVOToolRegistrationId");
                                });

                            b1.Navigation("Annotations");
                        });

                    b.Navigation("AuthConfig")
                        .IsRequired();

                    b.Navigation("ConnectionConfig")
                        .IsRequired();

                    b.Navigation("ToolSchema");
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.OwnsOne("CoreSRE.Domain.ValueObjects.WorkflowGraphVO", "Graph", b1 =>
                        {
                            b1.Property<Guid>("WorkflowDefinitionId");

                            b1.HasKey("WorkflowDefinitionId");

                            b1.ToTable("workflow_definitions");

                            b1
                                .ToJson("graph")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowDefinitionId");

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.WorkflowEdgeVO", "Edges", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowGraphVOWorkflowDefinitionId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Condition");

                                    b2.Property<string>("EdgeId")
                                        .IsRequired();

                                    b2.Property<string>("EdgeType")
                                        .IsRequired();

                                    b2.Property<string>("SourceNodeId")
                                        .IsRequired();

                                    b2.Property<string>("TargetNodeId")
                                        .IsRequired();

                                    b2.HasKey("WorkflowGraphVOWorkflowDefinitionId", "__synthesizedOrdinal");

                                    b2.ToTable("workflow_definitions");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowGraphVOWorkflowDefinitionId");
                                });

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.WorkflowNodeVO", "Nodes", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowGraphVOWorkflowDefinitionId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Config");

                                    b2.Property<string>("DisplayName")
                                        .IsRequired();

                                    b2.Property<string>("NodeId")
                                        .IsRequired();

                                    b2.Property<string>("NodeType")
                                        .IsRequired();

                                    b2.Property<Guid?>("ReferenceId");

                                    b2.HasKey("WorkflowGraphVOWorkflowDefinitionId", "__synthesizedOrdinal");

                                    b2.ToTable("workflow_definitions");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowGraphVOWorkflowDefinitionId");
                                });

                            b1.Navigation("Edges");

                            b1.Navigation("Nodes");
                        });

                    b.Navigation("Graph")
                        .IsRequired();
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.ToolRegistration", b =>
                {
                    b.Navigation("McpToolItems");
                });
#pragma warning restore 612, 618
        }
    }
}
