// <auto-generated />
using System;
using System.Text.Json;
using CoreSRE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreSRE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210053451_AddAgentSessions")]
    partial class AddAgentSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreSRE.Domain.Entities.AgentRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agent_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkflowRef")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_ref");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent_registrations", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.AgentSessionRecord", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("agent_id");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonElement>("SessionData")
                        .HasColumnType("jsonb")
                        .HasColumnName("session_data");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AgentId", "ConversationId");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_agent_sessions_agent_id");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("CoreSRE.Domain.Entities.AgentRegistration", b =>
                {
                    b.OwnsOne("CoreSRE.Domain.ValueObjects.AgentCardVO", "AgentCard", b1 =>
                        {
                            b1.Property<Guid>("AgentRegistrationId");

                            b1.HasKey("AgentRegistrationId");

                            b1.ToTable("agent_registrations");

                            b1
                                .ToJson("agent_card")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationId");

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.AgentInterfaceVO", "Interfaces", b2 =>
                                {
                                    b2.Property<Guid>("AgentCardVOAgentRegistrationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Path");

                                    b2.Property<string>("Protocol")
                                        .IsRequired();

                                    b2.HasKey("AgentCardVOAgentRegistrationId", "__synthesizedOrdinal");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("AgentCardVOAgentRegistrationId");
                                });

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.AgentSkillVO", "Skills", b2 =>
                                {
                                    b2.Property<Guid>("AgentCardVOAgentRegistrationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Description");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("AgentCardVOAgentRegistrationId", "__synthesizedOrdinal");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("AgentCardVOAgentRegistrationId");
                                });

                            b1.OwnsMany("CoreSRE.Domain.ValueObjects.SecuritySchemeVO", "SecuritySchemes", b2 =>
                                {
                                    b2.Property<Guid>("AgentCardVOAgentRegistrationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Parameters");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.HasKey("AgentCardVOAgentRegistrationId", "__synthesizedOrdinal");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("AgentCardVOAgentRegistrationId");
                                });

                            b1.Navigation("Interfaces");

                            b1.Navigation("SecuritySchemes");

                            b1.Navigation("Skills");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.HealthCheckVO", "HealthCheck", b1 =>
                        {
                            b1.Property<Guid>("AgentRegistrationId");

                            b1.Property<int>("FailureCount");

                            b1.Property<bool>("IsHealthy");

                            b1.Property<DateTime?>("LastCheckTime");

                            b1.HasKey("AgentRegistrationId");

                            b1.ToTable("agent_registrations");

                            b1
                                .ToJson("health_check")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationId");
                        });

                    b.OwnsOne("CoreSRE.Domain.ValueObjects.LlmConfigVO", "LlmConfig", b1 =>
                        {
                            b1.Property<Guid>("AgentRegistrationId");

                            b1.Property<string>("Instructions");

                            b1.Property<string>("ModelId")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("ToolRefs")
                                .IsRequired();

                            b1.HasKey("AgentRegistrationId");

                            b1.ToTable("agent_registrations");

                            b1
                                .ToJson("llm_config")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationId");
                        });

                    b.Navigation("AgentCard");

                    b.Navigation("HealthCheck")
                        .IsRequired();

                    b.Navigation("LlmConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
